version: "3"

services:
  cuckoo:
    image: hlcuckoo
    command: -d
    ports:
      - "2042:2042"
    networks:
      - cuckoo
    env_file:
      - ./files/config.env

  web:
    image: hlcuckoo
    command: web runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    networks:
      - cuckoo
    env_file:
      - ./files/config.env

  api:
    image: hlcuckoo
    command: api --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - cuckoo
    env_file:
      - ./files/config.env

networks:
  cuckoo:
    driver: bridge